### ISSUE TITLE
build error on OSX

### ISSUE THREAD

**Issue by aisk** [tomhrr/dale#30]
I build dale on OSX yosemite, follow this step:

```bash
brew install llvm
brew install libffi
cmake .. -DLLVM_CONFIG=/usr/local/Cellar/llvm/3.5.1/bin/llvm-config
```

Then I can run cmake successfully, but got an error on linking, this is the error information:

```
...
[ 74%] Building CXX object CMakeFiles/dalec.dir/src/dale/Operation/CloseScope/CloseScope.cpp.o
[ 75%] Building CXX object CMakeFiles/dalec.dir/src/dale/Form/Parameter/Parameter.cpp.o
[ 75%] Building CXX object CMakeFiles/dalec.dir/src/dale/Module/Reader/Reader.cpp.o
[ 76%] Building CXX object CMakeFiles/dalec.dir/src/dale/SavePoint/SavePoint.cpp.o
[ 77%] Building CXX object CMakeFiles/dalec.dir/src/dale/Form/Utils/Utils.cpp.o
Linking CXX executable dalec
clang: warning: argument unused during compilation: '-ansi'
ld: library not found for -ltinfo
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [dalec] Error 1
make[1]: *** [CMakeFiles/dalec.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by aisk** [comment]
I removed the -ansi, and change -ltinfo to -lncurses, the rerun make, got this error:

```
...
[ 75%] Building CXX object CMakeFiles/dalec.dir/src/dale/Module/Reader/Reader.cpp.o
[ 76%] Building CXX object CMakeFiles/dalec.dir/src/dale/SavePoint/SavePoint.cpp.o
[ 77%] Building CXX object CMakeFiles/dalec.dir/src/dale/Form/Utils/Utils.cpp.o
Linking CXX executable dalec
[ 77%] Built target dalec
Scanning dependencies of target drt
[ 78%] Generating libdrt.so
libdrt.s:2:2: error: unknown directive
 .macosx_version_min 14, 1
 ^
Assertion failed: (!res && "unable to make library"), function writeSharedObject, file /tmp/dale/src/dale/Module/Writer/Writer.cpp, line 91.
make[2]: *** [libdrt.so] Abort trap: 6
make[1]: *** [CMakeFiles/drt.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tomhrr** [comment]
Thanks for the report.  I don't have access to a Mac at the moment, and won't yet for a few days, so it may be a little while before this is fixed.

**Comment by BitPuffin** [comment]
Yeah I got more or less the same results, trying with brew versions of clang etc. It would be nice if it just worked with the xcode version of clang. It seems like the main thing that it screws up on is what seems to be an assembly directive to me:

```
[78%] Generating libdrt.so
libdrt.s:2:2: error: unknown directive
 .macosx_version_min 14, 1
```

When compiling Utils.cpp. But the assertion that fales is in Writer.cpp:

``` 
Assertion failed: (!res && "unable to make library"), function writeSharedObject, file /Users/isak/src/softlib/dale/src/dale/Module/Writer/Writer.cpp, line 91.
```

**Comment by tomhrr** [comment]
- On 10.9.2, compilation now reaches concept-defs, which fails, because concepts-core references _stderr, which can't be found.  This is probably due to non-portable assumptions about how the standard handles are implemented.
- Individual files can now be compiled and run, too (i.e. "make tests" gets a bit further along).

The core of the current "fix", which just filters the relevant unhandled parts of the assembly, is very short-term.  I don't know what the underlying cause is, but it may be due to a version mismatch between the system compiler and the version of LLVM installed by brew.  This is probably going to take a while longer yet.

**Comment by tomhrr** [comment]
This should work properly now.  The handling of the standard handles has been fixed, and the underlying problem with the assembly was due to a mismatch between the version of LLVM and the version of Clang, so the filtering hack has been removed and the documentation has been updated to suit.  This will be left open pending confirmation that the fix works for somebody else.

**Comment by tomhrr** [comment]
Closing for now, will reopen if it is reported again.

**Comment by BitPuffin** [comment]
I'm still unable to get it building. Here's a gist of what I am trying in case it's obviously wrong: https://gist.github.com/BitPuffin/2ab8c01a1be8d5019c56

**Comment by tomhrr** [comment]
Thanks.  I think the problem there is that although 'CC' is mapped correctly, the compiler executable depends on 'cc' (lowercase, unqualified) pointing to the correct version of clang.  Judging by the gist, rerunning after executing "ln -s /usr/local/opt/llvm/bin/clang /usr/local/bin/cc; export PATH=/usr/local/bin:$PATH" should do the job.

**Comment by BitPuffin** [comment]
Yeah that seems to have done the trick. I guess I'm gonna play with Dale a bit now then :) Hoping I can maybe use it for ios+android dev. Which I think should probably be alright because it pretty much just compiles to C right?

Cheers :) :+1:

**Comment by tomhrr** [comment]
The compiler cannot produce C, and at the moment, does not support cross-compilation.  I haven't tested it on ARM, either.  If the relevant build process allows for arbitrary LLVM IR or bitcode to be used, then things may work, but that's awkward and probably a long shot besides.  Best of luck :)

**Comment by BitPuffin** [comment]
Yeah I figured that out eventually. I'm already having a go at compiling it to bitcode and then passing it to the NDK Clang to see if that could work and I hope it might :) We'll see though. Cheers

**Comment by BitPuffin** [comment]
Not that it's relevant at all to the issue but I thought I'd let you know that I _FINALLY_ managed to get dale running on android, just by using the ir!

Image proof: http://a.pomf.se/tzivru.png

I called out to C from dale because I didn't wanna spend time writing up the entire JNIEnv struct for dale just to test if it would run.

I'm thinking maybe I'll write a tutorial or something on the wiki on how to set it up! I'm sure this doesn't mean that there are zero issues, for example I did report an issue. But it seems to me like it might be good enough to start playing with. I'll probably start making bindings to opengl es then and see if I can start making an android game with dale.

I did get it running as well in the ios simulator. I then wanted to test on my gf's iPhone but quickly realized that I have to give $99 to Apple just to test lol. So that's where that journey ended. I'm fairly confident though that it would work on ios as well though given that it works on android. NDK just recently got llvm support it seems so if an llvm integration that young can run dale then ios which has used llvm for ages should be able to. It's also the same cpu architecture etc.

Anyway I'll stop spamming this thread with nonsense now.
