### ISSUE TITLE
Segmentation fault with (@:@ <DNode> list-node) -- Add safer compile time execution?

### ISSUE THREAD

**Issue by BitPuffin** [tomhrr/dale#37]
``` racket
(import macros)
(import cstdio)
(import introspection)

(using-namespace std.macros
  (def def-type-macro (macro extern (new linkage old)
    (setv old (@:@ old list-node))
    (qq using-namespace std.macros
      (def (uq new) (macro (uq linkage) (void)
        (qq (uql old))))))))

(def-type-macro cstring extern (p (const char)))
(def-type-macro thingy extern int) ; this line causes segfault

(def main (fn extern-c void (void)
  (def a-string (var auto (cstring) "Yo dude"))
  (printf "string: %s\n" a-string)
  (return)))
```

I'm not sure if this should be considered a bug or not. It makes sense that trying to access the memory when it's not actually there would cause a segfault. However it feels like especially at compile time you don't want segmentation fault to be your only hint that something is wrong. So I think there needs to eventually be some solution that does checking at compile time that you aren't accessing memory you don't own. And report which line that causes the segmentation fault.

**Comment by tomhrr** [comment]
This is definitely a bug: `qq` is likely not checking any of its input, and should be.

**Comment by tomhrr** [comment]
`qq` now checks for null nodes at macro expansion time, and a separate macro expansion error is added to make things easier to track.  The above now produces the following on compilation:

    github-37.dt:10:13: error: unquoting null node (see macro at 8:5)
    github-37.dt:13:1: error: macro expansion error (see previous)

(Most of the time, the separate macro expansion error is not needed, since the macro error will be able to point to the correct node.  However, if the separate error is not shown across the board, it makes problems like the above pretty difficult to track down.)
