### ISSUE TITLE
Assertion failed when building on Yosemite with latest Developer Tools

### ISSUE THREAD

**Issue by oubiwann** [tomhrr/dale#42]
Mac OS X: 10.10.5
LLVM: 3.5.1
Dale: from master

Set up:

```
brew install llvm35
export PATH=/usr/local/Cellar/llvm35/3.5.1/lib/llvm-3.5/bin:$PATH
git clone git@github.com:tomhrr/dale.git
mkdir dale-build
cd dale-build
cmake ../dale
make
```

``cmake`` sets everything up just fine. ``make`` runs almost to the end with no error, then:

```
Scanning dependencies of target programs
[ 98%] Generating module-to-markdown
Assertion failed: ((i >= FTy->getNumParams() || \
FTy->getParamType(i) == Args[i]->getType()) &&  \ 
"Calling a function with a bad signature!"),
 function init, file Instructions.cpp, line 281.
make[2]: *** [module-to-markdown] Abort trap: 6
make[1]: *** [CMakeFiles/programs.dir/all] Error 2
make: *** [all] Error 2
```

Other info:

```
$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr
                 --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

Maybe it's a problem that Apple's LLVM/clang is based on LLVM 3.6 and I'm trying to build with 3.5?

Not sure how I should proceed -- either to get this working or to provide you with more information for debugging purposes ...

Ideas?

**Comment by tomhrr** [comment]
The LLVM/clang version difference can cause problems: see https://github.com/tomhrr/dale/blob/master/doc/1-2-setup.md#building-on-os-x for details on how to get Dale to use matching versions.  However, even with matching versions, --static-modules (a compiler flag) is not functioning correctly with this particular configuration.  That flag has now been removed from the module-to-markdown build step, so it should be possible to compile and run tests, though one particular test that also uses the --static-modules flag will fail.  Aside from that, a few other tests do not pass under an out-of-tree build.

The out-of-tree test problems will be easy to fix, and should be done within the next few days.  The --static-modules problem is likely to be more complicated, but since --static-modules is effectively an optimisation flag, it should still be possible to write/build/run Dale code under this configuration.

**Comment by oubiwann** [comment]
> The LLVM/clang version difference can cause problems: see
> https://github.com/tomhrr/dale/blob/master/doc/1-2-setup.md#building-on-os-x 

Yikes! Not sure how I missed that -- thanks. I pulled down your latest commits, though, and they seem to have allowed me to build successfully without making the setup changes you provided in that link.

However, when I attempted to run the compiled ``hello-world.dt``, I got this error:

```
$ ./a.out
dyld: Library not loaded: libcstdio-nomacros.so
  Referenced from: /Users/oubiwann/lab/lisp/dale-demos/./a.out
  Reason: image not found
Trace/BPT trap: 5
```

This is completely new territory for me (not a C coder by any stretch) -- I'll try rebuilding with the recommendations from that link.

**Comment by tomhrr** [comment]
That looks to be due to the problem described here: http://stackoverflow.com/questions/27506450/clang-change-dependent-shared-library-install-name-at-link-time.  I hadn't noticed it before, since on OS X I had only built and run tests, without installing and trying to compile programs from other directories.  Building the library with `-install_name @rpath/...` and including `-rpath` on executable compilation within the compiler should fix it, but I won't have access to a Mac with which to test for a few days yet, unfortunately.

**Comment by tomhrr** [comment]
Still a few things to do here, but passing `-L` options with the shared library directory paths when compiling the final executable should at least get things to run properly for the time being.

**Comment by tomhrr** [comment]
Compiling and running programs from other directories should now work correctly.  The --static-modules problem is still to be fixed, though.

**Comment by tomhrr** [comment]
The problem in the end was the use of a named struct type to represent the void pointer, which meant that a new void pointer type was created for each individual module, which in turn led to type-checking problems when --static-modules was used.  This is now fixed, so all tests should pass on OS X.  Thanks for this bug report.
