### ISSUE TITLE
Program doesn't build

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#49]
Error messages similar to this:
```
/home/porky11/tmp/dale/eg/module-to-markdown/module-to-markdown.dt:7:1: error: /usr/local/lib/dale/libderivations.dtm: No such file or directory
/home/porky11/tmp/dale/eg/module-to-markdown/module-to-markdown.dt:7:1: error: unable to load module 'derivations'
```

**Comment by tomhrr** [comment]
On Tue, Aug 09, 2016 at 05:56:09PM -0700, Fabio Krapohl wrote:
> Error messages similar to this:
>
> /home/porky11/tmp/dale/eg/module-to-markdown/module-to-markdown.dt:7:1: error: /usr/local/lib/dale/libderivations.dtm: No such file or directory
> /home/porky11/tmp/dale/eg/module-to-markdown/module-to-markdown.dt:7:1: error: unable to load module 'derivations'

I'm having trouble replicating this via 'make doc', at least with the
in-tree build approach.  By default, the compiler should be looking
through a series of directories (including the current directory)
before the /usr/local/lib/dale directory, and the build process should
be producing the relevant dtm file prior to trying to build
module-to-markdown.  The error message only refers to the
/usr/local/lib/dale directory because that's the last directory that's
checked.  Could you send the whole session?  Alternatively, could you
send the results of running 'make clean', and then 'make derivations'?

**Comment by tomhrr** [comment]
On Tue, Aug 09, 2016 at 05:56:09PM -0700, Fabio Krapohl wrote:
> ...

After looking at this further, it may have been due to incorrect
dependency specifications in the CMake file, which have now been
fixed.  Could you try pulling from the repository and rebuilding, and
see if that helps?

**Comment by porky11** [comment]
it works now, thanks
