### ISSUE TITLE
Bug when defining void functions and how to get pointer to void function

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#50]
This causes the compiler to corrupt:
```
(def a (var intern int 1))
(def a (fn intern int (void) 1))
```
I noticed, that getting a pointer to a void function doesn't work as expected:
`(# a void)` doesn't work, and `(# a)` seems to return an incorrect value (i used it as parameter for glutDisplayFunc)
So i tried to define it as a variable of the same name too too and the compiler corrupted.

**Comment by tomhrr** [comment]
On Thu, Aug 11, 2016 at 11:38:10AM -0700, Fabio Krapohl wrote:
> This causes the compiler to corrupt:
> 
> (def a (var intern int 1))
> (def a (fn intern int (void) 1))

Thanks, the bug was to do with symbol name overlap, and has now been
fixed.

> I noticed, that getting a pointer to a void function doesn't work as
> expected:
> `(# a void)` doesn't work, and `(# a)` seems to return an incorrect
> value (i used it as parameter for glutDisplayFunc)
> So i tried to define it as a variable of the same name too too and
> the compiler corrupted.

There's now an example GLUT program available at
https://github.com/tomhrr/dale/blob/master/eg/glut-example/glut-example.dt
(`dalec glut-example.dt -lGL -lGLU -lglut`), which may help to clarify
some of these things.  Assuming it does, any feedback you have about
improving the existing documentation to account for this would be
appreciated.
