### ISSUE TITLE
reference parameters

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#55]
```
(def x (fn intern void ((a (ref T)))))
```
seems to be the same as
```
(def _x (fn intern void ((a (p T)))))
(def x (macro inter (a)
  (qq _x (# (uq a)))))
```
something like this seems more clear to me:
```
(def x (fn intern void ((a (p T) #))))
```
`#` specifies the function called before the function is called with the argument as parameter
so something like this also will be possible:
```
(def x (fn intern void ((a (p T) q))))  ;automatic quoting of symbols without macros
(def x (fn intern void ((a (p T) (fn int ((x int)) (* 2 x))))))  ;automatic duplicating before function call

**Comment by tomhrr** [comment]
On Fri, Aug 26, 2016 at 01:54:20PM -0700, Fabio Krapohl wrote:
> (def x (fn intern void ((a (ref T)))))
>
> seems to be the same as
>
> (def _x (fn intern void ((a (p T)))))
> (def x (macro inter (a)
>   (qq _x (# (uq a)))))

It's the same in contexts where the differences between macros and
functions are not relevant.  An example of where those differences are
relevant is the max concept macro in the algorithms module.  That
macro is overloaded based on whether the argument type prefers
references: a type that does not prefer references gets a max like so:

    (def max (fn extern T ((a T) (b T))
      (if (> a b) a b)))

whereas a type that prefers references gets a max like so:

    (def max (fn extern (retval T) ((a (ref (const T)))
                                    (b (ref (const T))))
      (if (> (@ a) (@ b))
          (setf retval (@ a))
          (setf retval (@ b)))
      (return)))

Currently, in both cases, it's possible for the client to take the
address of the resulting max function and use it like any other
function pointer.  In an approach that relied on the use of macros
when reference parameters were required, that would no longer be
possible, because the language doesn't support taking the address of a
macro and using it like a normal function pointer.  I think that this
restriction is sufficiently problematic that it warrants the
implementation of reference types as core language constructs.

> something like this seems more clear to me:
>
> (def x (fn intern void ((a (p T) #))))
>
> # specifies the function called before the function is called with
> the argument as parameter
> so something like this also will be possible:
>
> (def x (fn intern void ((a (p T) q))))  ;automatic quoting of symbols without macros
> (def x (fn intern void ((a (p T) (fn int ((x int)) (* 2 x))))))  ;automatic quoting of symbols without macros

This sort of syntactic extension would mean that it would not be
possible to take the addresses of these functions and use them like
noraml function pointers.  I think the current setup, where it's
possible to take and use the address of every defined function, is
preferable.
