### ISSUE TITLE
Bug when defining enum in other namespace

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#56]
```
(def x.y
  (enum extern uint (a)))
```
causes segmentation fault

**Comment by tomhrr** [comment]
On Sat, Aug 27, 2016 at 03:33:07AM -0700, Fabio Krapohl wrote:
> (def x.y
>   (enum extern uint (a)))
>
> causes segmentation fault

The `def` forms do not currently handle qualified names properly.
Instead of adding them to the appropriate namespace, they are defined
within the current namespace with the given name.  Because of how
names with periods are handled elsewhere, this means that the binding
becomes unreachable.  For `enum`s, because a series of helper
functions are defined when the `enum` itself is defined, and those
helper functions assume that the `enum` type can be resolved, there is
no error checking, and a segmentation fault will occur in this case.

As a temporary fix, assertions have been added in this case so that a
(somewhat) useful error message is produced when this occurs.  The
proper fix is to allow all `def` forms to use qualified names, so that
the original example works as expected.  This issue will be left open
pending that fix.
