### ISSUE TITLE
Should concepts be automatical instantiated when used the first time

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#86]
Would just require the macro generated by  def-type-macro to instantiate the concept-macro before returning the type name.
Problem: may cause some unwanted compile-time-overhead when using some concept-macro-type very often because it will be checked every time if it is already instantiated

**Comment by tomhrr** [comment]
On Wed, Sep 07, 2016 at 12:04:08PM -0700, Fabio Krapohl wrote:
> Would just require the macro generated by  def-type-macro to
> instantiate the concept-macro before returning the type name.
> Problem: may cause some unwanted compile-time-overhead when using
> some concept-macro-type very often because it will be checked every
> time if it is already instantiated

I'm not sure I understand the suggestion.  Do you mean that concept
instantiation (e.g. "(std.concepts.instantiate Set {type})") should
implicitly try to implement the concepts required for {type}, rather
than just reporting that {type} doesn't implement a given concept, to
save {type}'s user from having to explicitly implement all the
required concepts?

**Comment by porky11** [comment]
Yes, that's what I meant, 
maybe also having both options (automatic implement or report error)

**Comment by tomhrr** [comment]
On Wed, Sep 07, 2016 at 11:30:49PM -0700, Fabio Krapohl wrote:
> Yes, that's what I meant, 
> maybe also having both options (automatic implement or report error)

The problem with automatically implementing required concepts is that
it would lead to ambiguity in situations where a type can implement
the concepts required by two different candidate concept macros.  For
example, 'min' and 'max' in the algorithms module have different
implementations depending on whether the type implements 'Type' or
'PreferRefs'.  Every type can implement 'PreferRefs', because it
imposes no additional requirements past those of 'Type' and is used
purely for dispatch: it is only meant to be implemented when the
author wants to avoid unnecessary copies for the given type.  While
this objection could be resolved by use of a 'force' mechanism akin to
the currently-implemented one, at that point it would seem easier to
just require authors to implement the relevant concepts explicitly.

**Comment by porky11** [comment]
concepts seem to have more use cases than i thought (interfaces, parametric types, multiple inheritance, default implementations with easy way of avoiding ambiguos implementation)

Another option would be only implement automatically, if not ambigous, else report an error, if not implemented explicitly.
but when the error messages show, what I have to implement, it won't be a big problem. It would lower the verbrosity much.

by the way, would it be easy to implement, when a type implements multiple versions of a functions to call both (like super in java, or even method combinations, but generated at compiletime)?

**Comment by tomhrr** [comment]
On Thu, Sep 08, 2016 at 12:15:06PM -0700, Fabio Krapohl wrote:
> Another option would be only implement automatically, if not ambigous, else report an error, if not implemented explicitly.

The problem with this approach is that it won't always be possible to
determine that ambiguity might arise.  For example:

    (def-concept-macro x extern ((T PreferRefs))
      ...)
    
    (def-concept-macro y extern ((T NotPreferRefs))
      ...)

    (def mys (struct intern ((a int))))
    (instantiate x mys)
    (instantiate y mys)

where 'NotPreferRefs' is a hypothetical concept requiring that
'PreferRefs' is not implemented by the type.  If concepts are
implemented automatically, then 'x' can be instantiated for any type,
without ambiguity.  However, that then means that 'y' cannot be
instantiated for those types.  While the 'y' instantiation will fail
with an error message as though 'PreferRefs' were explicitly
implemented (at least with the current implementation), such that it's
not technically ambiguous, it's still ambiguous at a more abstract
level, because it's not possible to determine which of 'x' or 'y' the
author actually needs.  If 'PreferRefs' has to be explicitly
implemented, however, it's clear (or at least, clearer) that the
author intends to do that, and it's not merely happening as a
side-effect of something else.

Another example is where the 'x' concept macro originally requires
only that 'T' implement 'Type', and then later changes such that 'T'
must implement 'PreferRefs'.  On recompilation of the original
program, the instantiation of 'y' will fail, which would be a
relatively confusing outcome from the author's perspective.

> by the way, would it be easy to implement, when a type implements multiple versions of a functions to call both (like super in java, or even method combinations, but generated at compiletime)?

I'm not sure that this would be easy, given the current
implementation.  In the 'super' case, too, I'm not sure that the extra
complexity would be worth it, given that there are other ways of
abstracting common required functionality.  For example, the standard
and 'PreferRefs' instances of various functions replicate the common
logic, but could equally well expand to macro calls that contained the
core logic.

**Comment by porky11** [comment]
A simple example, where a type could be implemented implicitely is the force form when instantiating concept-macros
```
(using-namespace std.macros
(using-namespace std.concepts
  (def force+ (macro intern (concept type)
    (qq do
      (implement (uq concept) (uq type))
      (force (uq concept) (uq type)))))
))
;;this should enable to do this
(instantiate cm (force+ C T))
;;where cm is a context-macro, C is a concept, and T is a type, which does not have to implement the concept.
;;this could also be written istead of
(implement C T)
(instantiate cm T)
;;force is not required, the new form is shorter, and you don't have to specify force, if some other version is defined for this macro

```

**Comment by porky11** [comment]
I found some nice behaviour, which I didn't find in the documentation is, that when multiple versions of a concept macro are defined, I don't have to force, when one of the types A refines the other B, then A is selected by default.

**Comment by tomhrr** [comment]
On Tue, Sep 13, 2016 at 02:53:22AM -0700, Fabio Krapohl wrote:
> I found some nice behaviour, which I didn't find in the documentation is, that when multiple versions of a concept macro are defined, I don't have to force, when one of the types A refines the other B, then A is selected by default.

Thanks, I've updated the docmentation to (try to) make this clearer.
Does this behaviour mean that you see less need for a 'force+'-style
macro?

**Comment by porky11** [comment]
I think, this behaviour makes no difference, but it's not important, I could also implement it another way.

**Comment by porky11** [comment]
What I really want are these things:
When a undefined function is called, but concepts for it exist, the function should try to instantiate the concept, by default. This could be implemented as a macro, which tries to instantiate a concept-macro and returns the form itself if successful, else reports an error and returns `(no-op)`. There should not be a generic way for all functions (like expanding `(f a b c)` to `(instantiate f A B C)`, where f is a function name and a, b and c are variables with types A, B and C) but special versions for different functions (like expanding `(+ a b)` to `(instantiate + A)` only if A and B are equal).
Type macros should check if the type is already defined, else try to instantiate the type and then return the typename (maybe only if the type exists). In this case it should be the same implementation for all type maros.
Instead of checking if a function exists, `implement` could check, if a function can be implemented for this type (and maybe even implement it), and in cases where it is needed, that a specific concept is defined for a type, it should try to instantiate it by default, instead of just reporting errors for this type.

Why this is useful:
When defining a new type, for that I already defined concept macros, I have to write something like this:
```
(instantiate Ball float 2)
(instantiate UniquePtr (Ball float 2))
(instantiate swap (UniquePtr (Ball float 2)))
(implement Swappable (UniquePtr (Ball float 2)))
(instantiate Vector (UniquePtr (Ball float 2)))
```
and maybe more.
When I want to change the the number-type or the dimension of my Ball-type, I have to change it everywhere, where a function is defined for this type using a concepts, and I have to change it everywhere, where type macros are arguments to type macros. So even if I write the code as generic as possible, I have to change many things until it works. Which is bad, if I want to change this often. A simple solution for this is writing a (concept-)macro for instantiating and implementing everything, but this isn't as intuitive as automatically instantiating most things.
You could still instantiate them in special way, with force, or implement single concepts, which will change the implementation of a type depending on this concept, but only will need to do this in special cases.

I currently don't see cases, where this would lead to problems.
I'll try to implement some of these features as macros, and maybe submit pull requests.

**Comment by tomhrr** [comment]
I definitely appreciate that implicit instantiation in the above cases
would be useful.  However, I'm not sure this would be possible to 
implement in the language itself, primarily because implicit 
instantiation would rely on 'invoke', and absent a definition that 
captured all possible uses, it's not clear how this could be done.  
Elevating concept macros into the language proper is a possibility, 
but the aim here is more about seeing what can be done in the language
itself when there's a small core, rather than expanding that core to 
cover each use case that can't be implemented in that way.

More practically: I'm not sure why a flat search-and-replace across
your codebase doesn't suffice when the 'Ball' type changes, but I may
be missing something very obvious.
