### ISSUE TITLE
Enable parsing files with dale-syntas at compile-time

### ISSUE THREAD

**Issue by porky11** [tomhrr/dale#99]
Include only works at toplevel
so I'd like a function working like this:
```
;;;;example-file
a
(b)
"c"
```
```
;;;;my-program.dale
(parse-file "example-file") ;;returns (a (b) "c")
;;or
(some-parsing-macro "example-file") ;;may expand to (do a (b) "c")
```
I could save my shaders in seperate files, and read at compile-time then. (Edit: For just parsing strings, this is too complicated)
Adding a single function, that takes a stream and returns a pointer to the next DNode, which is null, when error or end of file

**Comment by tomhrr** [comment]
On Wed, Sep 14, 2016 at 02:33:04AM -0700, Fabio Krapohl wrote:
> Include only works at toplevel
> so I'd like a function working like this:
>
> ;;;;example-file
> a
> (b)
> "c"
>
>
> ;;;;my-program.dale
> (parse-file "example-file") ;;returns (a (b) "c")
> ;;or
> (some-parsing-macro "example-file") ;;may expand to (do a (b) "c")
>
> I could save my shaders in seperate files, and read at compile-time then.
> Adding a single function, that takes a stream and returns a pointer to the next DNode, which is null, when error or end of file

'include' now works within procedures as well as at the toplevel,
mainly because bringing it within the compiler allows for parsing
error messages to be consistent with the existing ones.  Please let me
know if this is problematic.
